/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.twilio.guardrail

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification


class GuardrailGradlePluginPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.twilio.guardrail")

        then:
        project.tasks.findByName("generate") != null
    }
}
