/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.twilio.guardrail

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'com.twilio.guardrail' plugin.
 */
public class GuardrailGradlePluginPluginFunctionalTest extends Specification {
    def setup() {
        file('functionalTest').deleteDir()
    }

    def "can run task"() {
        given:
        def projectDir = new File("build/functionalTest")
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle") << ""
        new File(projectDir, "build.gradle") << """
            plugins {
                id('com.twilio.guardrail')
            }
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("blah")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("plugin placeholder")
    }

    File file(String name) {
        new File("build", name)
    }
}
