/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.twilio.guardrail

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

class GuardrailGradlePluginFunctionalTest extends Specification {
    def setup() {
        file('functionalTest').deleteDir()
    }

    def "can run task"() {
        given:
        def projectDir = new File("build/functionalTest")
        projectDir.mkdirs()
        def resourceDirs = new File("build/functionalTest/src/main/resources")
        resourceDirs.mkdirs()
        new File(projectDir, "settings.gradle") << ""
        new File(projectDir, "build.gradle") << """
            plugins {
                id('com.twilio.guardrail')
            }
            
            guardrail {
                petstoreV2 {
                    inputFile = file('src/main/resources/pet_store_v2.yml')
                    gen {
                        packageName = 'com.foobar.generated.pet_store_v2'
                    }
                }
                petstoreV3 {
                    inputFile = file('src/main/resources/pet_store_v3.yml')
                    gen {
                        packageName = 'com.foobar.generated.pet_store_v3'
                        language = 'java'
                        framework = 'dropwizard'
                    } 
                }
            }
        """

        new File(resourceDirs, "pet_store_v2.yml") <<
            this.getClass().getResource("/pet_store_v2.yml").text

        new File(resourceDirs, "pet_store_v3.yml") <<
            this.getClass().getResource("/pet_store_v3.yml").text

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("guardrail")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        !result.output.contains("Error")
    }

    File file(String name) {
        new File("build", name)
    }


}
