/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.twilio.guardrail

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
public class GuardrailGradlePluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.tasks.register("generate") {
            doLast {
                println("plugin placeholder")
            }
        }
    }
}
