name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '14', '15' ]
    steps:
    - uses: actions/checkout@v4
    - name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v2.1.0
    - name: Set up JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: print Java version
      run: java -version
    - uses: actions/cache@v4.0.0
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build
      run: ./gradlew build
