name: Release

on:
  release:
    types:
      - released
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v1.0.4
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'zulu'
    - name: print Java version
      run: java -version
    - name: Publish plugin
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      run: |
        mkdir -p ~/.gradle
        echo "gradle.publish.key=${GRADLE_PUBLISH_KEY}" > ~/.gradle/gradle.properties
        echo "gradle.publish.secret=${GRADLE_PUBLISH_SECRET}" >> ~/.gradle/gradle.properties
        ./gradlew build publishPlugins
